import { ProfileProps } from "@/components/profile-card";

// Profile data
const profiles: ProfileProps[] = [
  {
    id: "marcel-apitty-wcopilot-webflow-io",
    name: "Marcel Apitty",
    roles: ["Designer"],
    bio: "Creative UI/UX Designer based in Brazil.",
    website: "https://marcel-apitty-wcopilot.webflow.io",
  },
  {
    id: "dennissnellenberg-com",
    name: "Dennis Snellenberg",
    roles: ["Designer", "Developer"],
    bio: "Helping brands to stand out in the digital era.",
    website: "https://dennissnellenberg.com",
  },
  {
    id: "martin-laxenaire-fr",
    name: "Martin Laxenaire",
    roles: ["Developer"],
    bio: "Front-end developer based in Lyon, France",
    website: "https://www.martin-laxenaire.fr",
  },
  {
    id: "emilkowal-ski",
    name: "Emil Kowalski",
    roles: ["Designer"],
    bio: "Design Engineer at Linear.",
    website: "https://emilkowal.ski",
  },
  {
    id: "antfu-me",
    name: "Anthony Fu",
    roles: ["Developer"],
    bio: "Hey, I am Anthony Fu, a fanatical open sourceror, and a design engineer.",
    website: "https://antfu.me",
  },
  {
    id: "jonhargreaves-com",
    name: "Jon Hargreaves",
    roles: ["Designer"],
    bio: "Senior Product Designer at QuickNode and the Founder of Coffee Club.",
    website: "https://www.jonhargreaves.com",
  },
  {
    id: "pedropeguerojr-com",
    name: "Pedro Peguero Jr.",
    roles: ["Designer"],
    bio: "Art Director and Designer living in Brooklyn, NY",
    website: "https://www.pedropeguerojr.com",
  },
  {
    id: "igorstumberger-com",
    name: "Igor Štumberger",
    roles: ["Designer"],
    bio: "Senior Product Designer with a love for code and technology.",
    website: "https://igorstumberger.com",
  },
  {
    id: "nicknoble-works",
    name: "Nick Noble",
    roles: ["Designer"],
    bio: "Building better teams and smaller software @ Miniware.",
    website: "https://nicknoble.works",
  },
  {
    id: "robb-is",
    name: "Robb Böhnke",
    roles: ["Designer", "Developer"],
    bio: "Developer & Designer based in Berlin, Germany.",
    website: "https://robb.is/",
  },
  {
    id: "rauno-me",
    name: "Rauno Freiberg",
    roles: ["Developer"],
    bio: "",
    website: "https://rauno.me",
  },
  {
    id: "david-mendes-com",
    name: "David Mendes",
    roles: ["Designer"],
    bio: "Curious designer, bad skateboarder, frustrated musician.",
    website: "https://www.david-mendes.com",
  },
  {
    id: "cydstumpel-nl",
    name: "Cyd Stumpel",
    roles: ["Developer"],
    bio: "Creative Developer & Teacher from Amsterdam, The Netherlands.",
    website: "https://cydstumpel.nl",
  },
  {
    id: "praveenjuge-com",
    name: "Praveen Juge",
    roles: ["Designer"],
    bio: "What’s up nerds? I’m Praveen Juge, a designer and developer.",
    website: "https://praveenjuge.com",
  },
  {
    id: "ibelick-com",
    name: "Julien Thibeaut",
    roles: ["Designer"],
    bio: "Building software with a focus on design, motion, and detail.",
    website: "https://ibelick.com",
  },
  {
    id: "mitul-ca",
    name: "Mitul Shah",
    roles: ["Designer"],
    bio: "Photographer, design engineer, and a bit more.",
    website: "https://mitul.ca",
  },
  {
    id: "taurean-work",
    name: "Taurean Bryant",
    roles: ["Designer"],
    bio: "Designer-turned-engineer with a deep love of the web.",
    website: "https://taurean.work",
  },
  {
    id: "paco-me",
    name: "Paco Coursey",
    roles: ["Developer"],
    bio: "Crafting interfaces. Building polished software and web experiences.",
    website: "https://paco.me",
  },
];

export default profiles;
