import { ProfileProps } from "@/components/profile-card";

// Profile data
const profiles: ProfileProps[] = [
  {
    id: "heylucy-studio",
    name: "Lucia Codreanu",
    roles: ["Designer"],
    bio: "A one-woman-band design studio that provides designs that deliver, with no fluff and no extras.",
    website: "https://heylucy.studio",
  },
  {
    id: "buszewski-com",
    name: "Tomasz Buszewski",
    roles: ["Designer", "Developer"],
    bio: "Web designer and developer with 17 years of experience.",
    website: "https://buszewski.com",
  },
  {
    id: "lucasrees-com",
    name: "Lucas Rees",
    roles: ["Designer", "Developer"],
    bio: "Designer, code writer & maker of things – habitual beginner and ‘learn-aholic’ with roughly 15 years of experience in creation and code",
    website: "https://www.lucasrees.com",
  },
  {
    id: "soahil",
    name: "Soahil",
    roles: ["Designer", "Developer"],
    bio: "A full-stack software engineer with a passion for crafting impactful solutions. I team up with forward-thinking founders and investors to turn their cutting-edge ideas into tangible, market-ready products.",
    website: "https://mrsohail.one",
  },
  {
    id: "sam-marxz-com",
    name: "Sam Marxz",
    roles: ["Designer", "Developer"],
    bio: "UI/UX Designer & Front-End Developer specializing in digital experiences that merge thoughtful design with clean code. Passionate about creating interfaces that tell stories and solve real problems.",
    website: "https://marxz.me",
    image:
      "https://minimal.gallery/wp-content/uploads/2025/02/www.marxz_.me_-900x500.png",
  },
  {
    id: "komandin-com",
    name: "Anton",
    roles: ["Designer"],
    bio: "Anton Komandin — experience designer. Websites for companies giving better customer experience.",
    website: "https://komandin.com/en",
  },
  {
    id: "jasonwalkow-com",
    name: "Jason Walkow",
    roles: ["Designer", "Developer"],
    bio: "Creative founder based in Los Angeles. Head of Design at Plain Sight Ventures.",
    website: "https://jasonwalkow.com",
  },
  {
    id: "jonaspelzer-com",
    name: "Jonas Pelzer",
    roles: ["Designer", "Developer"],
    bio: "Designer combining visual and interactive design to create digital experiences.",
    website: "https://jonaspelzer.com",
  },
  {
    id: "chester-how",
    name: "Chester",
    roles: ["Developer"],
    bio: "Product engineer at Mobbin.",
    website: "https://chester.how",
  },
  {
    id: "jonyablonski-com",
    name: "Jon Yablonski",
    roles: ["Designer"],
    bio: "Senior Product Designer @Mixpanel, author & creator of Laws of UX, creator of Humane by Design, and co-organizer of IXD2.",
    website: "https://jonyablonski.com",
  },
  {
    id: "carlbeaverson-com",
    name: "Carl Beaverson",
    roles: ["Developer"],
    bio: "Creative web developer from Australia, collaborating with designers and agencies.",
    website: "https://carlbeaverson.com",
  },
  {
    id: "hem-so",
    name: "Hemanth Soni",
    roles: ["Developer"],
    bio: "Growth expert in financial services, data infrastructure, and crypto.",
    website: "https://hem.so",
  },
  {
    id: "bradfrost-com",
    name: "Brad Frost",
    roles: ["Designer", "Developer", "Writer"],
    bio: "Web designer & developer, speaker, writer, teacher, and much more. ",
    website: "https://bradfrost.com",
  },
  {
    id: "andersbakken-com",
    name: "Anders Bakken",
    roles: ["Designer"],
    bio: "Designer & art director creating visual identities, design systems, and websites.",
    website: "https://andersbakken.com",
  },

  {
    id: "peter-arendt",
    name: "Peter Arendt",
    roles: ["Designer", "Developer"],
    bio: "Front-end web developer & designer based in Warsaw, Poland.",
    website: "https://peterarendt.com",
  },

  {
    id: "tonykahn-org",
    name: "Tony Kahn",
    roles: ["Writer"],
    bio: "40+ year veteran Senior Producer and Host for NPR and public radio WGBH.",
    website: "https://tonykahn.org",
  },
  {
    id: "andreaperato-com",
    name: "Andrea Perato",
    roles: ["Designer"],
    bio: "Creative Designer based in Milan.",
    website: "https://www.andreaperato.com",
  },
  {
    id: "thalles.work",
    name: "Thalles Lopes",
    roles: ["Designer", "Developer"],
    bio: "Creative Developer and Digital Designer based in São Paulo, Brazil.",
    website: "https://thalles.work",
  },
  {
    id: "cassandratang-com",
    name: "Cassandra Tang",
    roles: ["Designer"],
    bio: "Senior Product Designer at Remote, based in the UK.",
    website: "https://www.cassandratang.com",
  },

  {
    id: "bryanhidalgo-com",
    name: "Bryan Hidalgo",
    roles: ["Designer", "Developer"],
    bio: "Design Engineer based in Montreal, Canada.",
    website: "https://www.bryanhidalgo.com",
  },
  {
    id: "carlhauser.com",
    name: "Sebastian (Carl Hauser)",
    roles: ["Designer"],
    bio: "Multi-disciplinary designer from Germany, based in Tokyo. Head of Design at Analogue",
    website: "https://www.carlhauser.com",
    image:
      "https://minimal.gallery/wp-content/uploads/2025/04/www.carlhauser.com_-2048x1138.png",
  },

  {
    id: "andychung-me",
    name: "Andy Chung",
    roles: ["Designer"],
    bio: "Designer in West Berkeley, CA.",
    website: "https://andychung.me/",
    image:
      "https://minimal.gallery/wp-content/uploads/2020/11/49169cb4ea710de6e9bc8380f9ef5cb7fa65ce11.png",
  },
  {
    id: "p-cv",
    name: "Paul Macgregor",
    roles: ["Designer"],
    bio: "Designer at Linear, based in UK.",
    website: "https://p.cv",
    image:
      "https://minimal.gallery/wp-content/uploads/2024/12/p.cv_-2048x1138.png",
  },
  {
    id: "gracewalker-ca",
    name: "Grace Walker",
    roles: ["Designer"],
    bio: "An independent designer working with companies at the edge of new frontiers.",
    website: "https://www.gracewalker.ca",
    image:
      "https://minimal.gallery/wp-content/uploads/2024/09/www.gracewalker.ca_-900x500.png",
  },
  {
    id: "sidney-me",
    name: "Sidney Alcantara",
    roles: ["Designer"],
    bio: "Design Engineer at Canva based in Sydney.",
    website: "https://sidney.me",
    image:
      "https://minimal.gallery/wp-content/uploads/2023/05/sidney-alcantara-2048x1138.jpg",
  },
  {
    id: "andyrader-com",
    name: "Andy Rader",
    roles: ["Designer", "Developer"],
    bio: "Designer and front-end developer based in Berlin, Germany.",
    website: "https://www.andyrader.com",
    image:
      "https://minimal.gallery/wp-content/uploads/2023/02/andy-rader-2048x1138.jpg",
  },
  {
    id: "tobiasthaden-com",
    name: "Tobias Thaden",
    roles: ["Developer", "Designer"],
    bio: "Tobias Thaden is a software developer and product designer.",
    website: "https://tobiasthaden.com",
    image:
      "https://minimal.gallery/wp-content/uploads/2020/11/tumblr_pgp1u8f8sT1sjvgq8o1_1280-900x500.png",
  },
  {
    id: "matejbaco-eu",
    name: "Matej Bačo",
    roles: ["Developer"],
    bio: "Impact-driven software engineer from Czech Republic in love with everything open source.",
    website: "https://www.matejbaco.eu",
  },
  {
    id: "richbrown-info",
    name: "Rich Brown",
    roles: ["Designer"],
    bio: "Freelance UX/UI designer and art director.",
    website: "https://www.richbrown.info",
  },
  {
    id: "thomas-quigley",
    name: "Thomas Quigley",
    roles: ["Designer"],
    bio: "Designer based in New York City.",
    website: "https://www.quigley.work",
    image:
      "https://minimal.gallery/wp-content/uploads/2023/04/Screenshot-2023-04-25-at-18.47.33-900x500.png",
  },
  {
    id: "sanju-sh",
    name: "Sanju S.",
    roles: ["Designer"],
    bio: "Designer Founder at ThisUX & Google Developer Expert for Android",
    website: "https://www.sanju.sh",
  },
  {
    id: "marcel-apitty-wcopilot-webflow-io",
    name: "Marcel Apitty",
    roles: ["Designer"],
    bio: "Creative UI/UX Designer based in Brazil.",
    website: "https://marcel-apitty-wcopilot.webflow.io",
    image:
      "https://assets.awwwards.com/awards/media/cache/thumb_880_660/submissions/2024/01/65a8ecabf32a3844480038.png",
  },
  {
    id: "dennissnellenberg-com",
    name: "Dennis Snellenberg",
    roles: ["Designer", "Developer"],
    bio: "Helping brands to stand out in the digital era.",
    website: "https://dennissnellenberg.com",
    video:
      "https://assets.awwwards.com/awards/sites_of_the_day/2022/06/dennissnellenberg-1600x1200-opti.mp4",
  },
  {
    id: "martin-laxenaire-fr",
    name: "Martin Laxenaire",
    roles: ["Developer"],
    bio: "Front-end developer based in Lyon, France",
    website: "https://www.martin-laxenaire.fr",
  },
  {
    id: "emilkowal-ski",
    name: "Emil Kowalski",
    roles: ["Designer"],
    bio: "Design Engineer at Linear.",
    website: "https://emilkowal.ski",
  },
  {
    id: "antfu-me",
    name: "Anthony Fu",
    roles: ["Developer"],
    bio: "Hey, I am Anthony Fu, a fanatical open sourceror, and a design engineer.",
    website: "https://antfu.me",
  },
  {
    id: "jonhargreaves-com",
    name: "Jon Hargreaves",
    roles: ["Designer"],
    bio: "Senior Product Designer at QuickNode and the Founder of Coffee Club.",
    website: "https://www.jonhargreaves.com",
  },
  {
    id: "pedropeguerojr-com",
    name: "Pedro Peguero Jr.",
    roles: ["Designer"],
    bio: "Art Director and Designer living in Brooklyn, NY",
    website: "https://www.pedropeguerojr.com",
  },
  {
    id: "igorstumberger-com",
    name: "Igor Štumberger",
    roles: ["Designer"],
    bio: "Senior Product Designer with a love for code and technology.",
    website: "https://igorstumberger.com",
  },
  {
    id: "nicknoble-works",
    name: "Nick Noble",
    roles: ["Designer"],
    bio: "Building better teams and smaller software @ Miniware.",
    website: "https://nicknoble.works",
  },
  {
    id: "robb-is",
    name: "Robb Böhnke",
    roles: ["Designer", "Developer"],
    bio: "Developer & Designer based in Berlin, Germany.",
    website: "https://robb.is/",
  },
  {
    id: "rauno-me",
    name: "Rauno Freiberg",
    roles: ["Developer"],
    bio: "",
    website: "https://rauno.me",
  },
  {
    id: "david-mendes-com",
    name: "David Mendes",
    roles: ["Designer"],
    bio: "Curious designer, bad skateboarder, frustrated musician.",
    website: "https://www.david-mendes.com",
  },
  {
    id: "cydstumpel-nl",
    name: "Cyd Stumpel",
    roles: ["Developer"],
    bio: "Creative Developer & Teacher from Amsterdam, The Netherlands.",
    website: "https://cydstumpel.nl",
  },
  {
    id: "praveenjuge-com",
    name: "Praveen Juge",
    roles: ["Designer"],
    bio: "What’s up nerds? I’m Praveen Juge, a designer and developer.",
    website: "https://praveenjuge.com",
  },
  {
    id: "ibelick-com",
    name: "Julien Thibeaut",
    roles: ["Designer"],
    bio: "Building software with a focus on design, motion, and detail.",
    website: "https://ibelick.com",
  },
  {
    id: "mitul-ca",
    name: "Mitul Shah",
    roles: ["Designer"],
    bio: "Photographer, design engineer, and a bit more.",
    website: "https://mitul.ca",
  },
  {
    id: "taurean-work",
    name: "Taurean Bryant",
    roles: ["Designer"],
    bio: "Designer-turned-engineer with a deep love of the web.",
    website: "https://taurean.work",
  },
  {
    id: "paco-me",
    name: "Paco Coursey",
    roles: ["Developer"],
    bio: "Crafting interfaces. Building polished software and web experiences.",
    website: "https://paco.me",
  },
];

export default profiles;
